# docker build -t webcapture .
# docker run --user 1000:1000 -v $PWD/out:/tmp webcapture capture.js http://www.kandou.com/ /tmp/aaa.png
# docker run --user 1000:1000 -v $PWD/out:/tmp webcapture multiple_capture.js /tmp http://www.epfl.ch/ http://www.kandou.com/
FROM node:10-jessie-slim

RUN apt-get update && \
apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont \
ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget && \
wget https://github.com/Yelp/dumb-init/releases/download/v1.2.1/dumb-init_1.2.1_amd64.deb && \
dpkg -i dumb-init_*.deb && rm -f dumb-init_*.deb && \
apt-get clean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

COPY ./app /app
RUN chown -R 1000:1000 /app

WORKDIR /app
USER 1000
RUN npm install

ENTRYPOINT ["node"]
